name: Daily Check-in

on:
  schedule:
    #- cron: '0 1 * * *'  # 每天1点 UTC 时间执行
    - cron: "36 1,7 * * *"

  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 20            ## 限制运行时间在20分钟内，超出自动取消
    #if: ${{ github.event.repository.private }}   ## 限制在私有仓库下运行
    steps:
      - uses: actions/checkout@main
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
          LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
          BROWSE_ENABLED: ${{ secrets.BROWSE_ENABLED }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: |
          python main.py

      - name: Random Cron
        env:
          PAT: ${{ secrets.PAT }}
        if: always() && env.PAT
        uses: grbnb/random-workflow-cron@v2
        with:
          github_token: ${{ secrets.PAT }}   ## 具有workflow权限的PAT密钥 教程https://github.com/grbnb/random-workflow-cron/blob/v2/README.md#troubleshooting
          #push_switch: false
          keep_history: true
          time_zone: "UTC+8"
          hour_start: 0
          hour_end: 21
          interval_count: 2
